### ISSUE TITLE
Weapon Mod Issues

### ISSUE THREAD

**Issue by Drift72032** [Jimk72/Icarus_Mods#1]
Hey Jim, 

Love the mods.  For some reason I can't get the weapon mod to work.  The images just show question marks when in the crafting bench and won't let you craft.  Can you assist?

**Comment by Jimk72** [comment]
They were prob outdated. They are updated for this week. Redownload and install should fix the issue. Also if your using with other mods they need to be installed(merged) with mod manager.

**Comment by Drift72032** [comment]
Thanks!!!
