### ISSUE TITLE
Jimk_Easy_Cave Thumper

### ISSUE THREAD

**Issue by HungryBytesApps** [Jimk72/Icarus_Mods#10]
Hi there,

I'm using the Jimk_Easy_Cave mod using the mod manager to prevent worms from spawning. But when I activate a Thumper, sh*t hits the fan and the worms (even the big ones) spawn. Is it suppose to work like this? If so, is it possible to create a 2nd mod that also prevents spawning worms by a Thumper?

**Comment by Jimk72** [comment]
Yea that's only for cave worms. The thumper uses a different spawner.
