### ISSUE TITLE
Building height strength

### ISSUE THREAD

**Issue by msknibb** [Jimk72/Icarus_Mods#12]
Big fan of your mods Jimk. We have an issue with this mod, where it crashes the game as soon as we attempt to build something structural like a foundation, floor, wall etc. I know it's this mod causing the crash as I have done various testing of mods and after removing this mod, game works fine, though some of our structures fail. We have put our world on hold until this is fixed, are you able to take a look and fix this please?

**Comment by Jimk72** [comment]
Yea For a quick solution just remove the files called BP_Building_Base.uasset and  BP_Building_Base.uexp , Located in mods folder   Building_Height_Strength\BP\Building

**Comment by msknibb** [comment]
Thanks, that worked.
