### ISSUE TITLE
Jimk Added Deployables

### ISSUE THREAD

**Issue by InfinitxLoop** [Jimk72/Icarus_Mods#18]
![Jimk](https://github.com/Jimk72/Icarus_Mods/assets/121468831/f1ace3f5-fd1a-45c0-a41a-29ba2c105036)

After the new update the mod causes this fatal error and crashes immediately upon opening the game.

**Comment by Jimk72** [comment]
Thank you for reporting. I am aware and should have a fix by Saturday afternoon.

**Comment by InfinitxLoop** [comment]
> Thank you for reporting. I am aware and should have a fix by Saturday afternoon.

A pleasure and thank you for the mods Jimk.
