### ISSUE TITLE
no issue just questions. apologies, wasnt sure how else to send text.

### ISSUE THREAD

**Issue by DigitalDan89** [Jimk72/Icarus_Mods#2]
So I used to be able to craft 5x bone arrows but now I am unable to and cannot find a way to do that again. Also am not sure the teleporter is working as I cannot locate where to craft it. I assumed it just wasn't working. Lastly, item stacks is also not working. Still have the default stack size.  I tried the manager but my game wouldn't open whenever I installed it so I just been inputting them all manually. Really appreciate any feedback and thank you for these awesome mods. Really makes the game more enjoyable. Even with the mods I feel like all I ever do is constantly mine and hunt. I have so much meat I just drop it now. I just need bones for the arrows. Thanks again , take care. Almost forgot, is it possible to get the flashlight direction based on mouse location so it can be pointed up and down as well as side to side?

**Comment by Jimk72** [comment]
The Teleporter is in the workshop. Just to the left of your initial suit. If you downloaded them Friday they were prob not updated for this week. I work a lot so I dont get time to update my mods till usually the weekend.
The teleporter is explained in this video I did: https://youtu.be/ggQ-qWpRI5k

**Comment by DigitalDan89** [comment]
Thank you for the info.  I been pretty good on keeping them up to date.  I
will check to be sure.  As of yesterday my large storage chest will no
longer let me place it down. Not sure if it's related but if you get any
other complaints of this then we will have a starting point. Lol. No
worries as far as updates and what not. I understand how much time work
consumes. I really appreciate what you do though. 😅 Take care and thank
you for the response.
