### ISSUE TITLE
having problems with your windmill mod for icarus not acepting cobections in curent icarus version

### ISSUE THREAD

**Issue by RaShCl** [Jimk72/Icarus_Mods#21]
First off let me thank you for your great mods they help me a lot and are not to complicated

I was logging in to teh game, and suddenly my deep ore drills weren't working anymore.
The cable system was ok from the windmill to teh drills.
So i removed the cables and tried to rewire them, then i got the following problem,

I couldn't connect an electric cable to teh windmill for some reason, the puck doesn't want to be added to it.
also running a cable from teh windmill first towards teh drills didn't work, whatever i tried i couldn't click teh electric cable on the windmill.

I did try the electric windmill that came with the game itself, and that's np, everything works, and so do the solar panels.

I know there was a big update to the electric system.

I also did check Icarus mod manager that i use for all your mods, even did the update data folder and the update installed mods, before i started Icarus, no errors there whatsoever.

in teh end I haven't been able to contact a cable to it anymore as of this date.

i like this mod very much, the mod manger  version lists it as all versions, so maybe i di something wrong, have n o clue at all.
if the mod is having a conflict with teh latest version of icarus, then i hope your able to fix it, because again i love this mod its so handy 

thx  for it, its appreciated

John

**Comment by Jimk72** [comment]
Make sure your are using the latest version! The devs re did the entire electrical system in the game 2 weeks ago. I have redone the windmill and my large wind turbine to address these issues.

**Comment by RaShCl** [comment]
i did aloow the update data folders and did a update windmill mod, maybe i
need to download a new version from your github, itself i have no clue as a
noob
or should update the modmanager stuff be enough
thx

**Comment by Jimk72** [comment]
Yes you will have to re download it. If using IMM just go to the download mods section and select my windmill mod(double click) to download and extract the new version. Select yes to replace existing mod. Once that is done re merge your mods you want in IMM and run the game and you should be good to go.

**Comment by Jimk72** [comment]
Never mind lol just seen you updated your post. I'll look into the date.

**Comment by RaShCl** [comment]
remerge your mods ?? never ehart of that.
i saw a option in IMM, something about putting all mods in one file
but have no clue  how that works, i did had at some pint all mods in the extracted tabs, and a file called merged or something
if that's what you mean.

right now i have all mods  installed  personally not in 1 file
