### ISSUE TITLE
Cannot craft Laika update items when mods installed

### ISSUE THREAD

**Issue by Mickroz** [Jimk72/Icarus_Mods#23]
Only have a few mods installed:
Intreeg's 4XP
Increase Stacks
Teleporter

Now with only the Increase stacks mod installed, i can craft the items, but some items are missing icons or have a different name, for example, the icon for marble kitchen storage is missing, and the ranching station is called barnyard workstation.
With the teleporter mod added i cannot craft the stations, its missing name and icon.
i don't think intreeg's xp mod  is altering craftable items.

**Comment by Jimk72** [comment]
You're installing them with my mod manager and the data folder is updated correct?

**Comment by Mickroz** [comment]
some feedback this, both me and my brother had this issue, he had it before, only way to fix this is to reinstall icarus, and then reinstall the mods, after that almost everything worked fine, but we both lost our teleporter remote, and cannot craft it anymore since it changed in the workshop.

**Comment by Jimk72** [comment]
Are you saying you have to unlock it again or it cant be crafted anymore?

**Comment by Mickroz** [comment]
> Are you saying you have to unlock it again or it cant be crafted anymore?
> 

Unlock it again.
