### ISSUE TITLE
Missing firearms tree in workshop

### ISSUE THREAD

**Issue by Mickroz** [Jimk72/Icarus_Mods#25]
As title says, missing firearms tree in workshop.
Removing teleporter mod 2.3 bring it back, but missing ammo box icon and crafted ammoboxes.
removing Increase Stacks Mod 3.3 brings back the icon in tree aswell the crafted ammoboxes.

**Comment by Jimk72** [comment]
Just downloaded them in IMM to make sure my versions were the same, added to game and no issues with workshop items with either mod and both mods installed. Make sure you are re merging your mods each week after the update. Also make sure IMM has updated the data folder. If you are playing on server make sure server also has the new IMM_MergedMod that you game has.

**Comment by Mickroz** [comment]
Ok... please tell me where im missing a step then, because my brother had the pistols in the workshop tree because icarus couldn't load his imm merged mods file, but mine worked when he loaded that.
Stopping server.
Deleting mods on server.
Deleting mods on game folder.
Download Mods -> Update local database -> Show avail. Update -> Download when avail.
Load mods list template.
Install All Listed Mods.
Upload merged mods file from game folder to server.
start server.
start icarus and join server.

**Comment by Jimk72** [comment]
You are only merging those two mods? When you downloaded the teleporter mod it was my mod not a release someone else posted?

**Comment by Mickroz** [comment]
No, 1 more, the 4xp mod, dunnow from whom, but, i think i figured it out, i thought i only had to update data folder once when installing imm, and then it would reas automatically from that when installing mods. 
So i did it before installing mods from list, and it works now.
I probably missed that part when watching your vids.

**Comment by Jimk72** [comment]
Ok glad you got it working. Sent from my iPhoneOn Jun 19, 2024, at 12:28 PM, Mickroz ***@***.***> wrote:﻿
No, 1 more, the 4xp mod, dunnow from whom, but, i think i figured it out, i thought i only had to update data folder once when installing imm, and then it would reas automatically from that when installing mods.
So i did it before installing mods from list, and it works now.
I probably missed that part when watching your vids.
