### ISSUE TITLE
Bear Mounts Never Get Hungry/Thirsty and Can't Level Up + Saddle Issue

### ISSUE THREAD

**Issue by Zsynh** [Jimk72/Icarus_Mods#29]
Hi there -

I have 2 bear mounts, and they never go below 100% hunger/thirst, and they have no "skills" tab in their inventory. 

They matured and immediately had 10 skill points available in the GUI area where a "Skills" tab would be - the number is yellow and glowing - but there's no way to access them since that tab doesn't exist. The health pool gets bigger as they level up, but the 10 phantom points number never changes.

They do take damage, and they do use the troughs, but they don't seem to actually need to. Kind of a handy bug. :) 

This last one may be intentional - only the Basic Saddle can be equipped on bear mounts.

They're great mounts though, thanks for making this.

**Comment by Jimk72** [comment]
Yes I made them a long time ago when only one saddle was avail. Bears are not set up for feed so To prevent them from starving I had to keep it at 100%. I planned on redoing them with all the new features but I see they have added a large bear trap to the game files so am waiting to see if they add the bear tame ability to base game.

**Comment by airynd** [comment]
Right on, thanks for the reply! That all makes sense.
