### ISSUE TITLE
No issue - question for you

### ISSUE THREAD

**Issue by Haalk2715** [Jimk72/Icarus_Mods#3]
Hi Jimk72,

Do you run a dedicated hosted Icarus server? If, yes public or private?

I just setup my own hosted dedicated server running your mods.  It's private but I can give you password if you want to try it out.

Thx
Haalk

**Comment by Jimk72** [comment]
Thanks but yea I just built my server. It’s currently running but not updated. Waiting till beta is over before playing on it again. But thank anyway!Sent from my iPhoneOn Dec 30, 2022, at 10:19 AM, Haalk2715 ***@***.***> wrote:﻿
Hi Jimk72,
Do you run a dedicated hosted Icarus server? If, yes public or private?
I just setup my own hosted dedicated server running your mods.  It's private but I can give you password if you want to try it out.
Thx
Haalk

**Comment by Haalk2715** [comment]
Cool stuff

Thank for getting back to me
