### ISSUE TITLE
Enhancement - Increase Stacks - new items

### ISSUE THREAD

**Issue by QualityRobD** [Jimk72/Icarus_Mods#31]
### Mod Name
- `Increase Stacks`

### Enhancement Description
- Update mod to allow enhanced stacking for:
    - `refined wood`
    - `concrete mix`
    - `electronics`

### Supporting Screenshot
<img src="https://github.com/user-attachments/assets/71db45e0-fec9-4cc4-8dc9-c20b9e3c4de7" width="450">

**Comment by Jimk72** [comment]
I should have time this weekend to update those items.

**Comment by QualityRobD** [comment]
You rock!

**Comment by Jimk72** [comment]
New version 3.4 is up. Added all the new food items also.

**Comment by Jimk72** [comment]
> You rock! I'm a coder but am unfamiliar with xmodz or modding in general. I'd be open to helping out, I'm just unfamiliar with the xmodz filetype.

The Exmodz file is just a zipped(compressed) Exmod file which is a text file that contains all the mods extracted changes. ExMod-Extracted Mod. IMM just takes the mods people make and extracts all the different json entries when compared to the games original. Then that extracted mod is re merged back into the new weekly json files to be compatible with that week.

**Comment by Jimk72** [comment]
If you come across any other items that need updated sizes just let me know.

**Comment by QualityRobD** [comment]
@Jimk72, arrows from the ship stack in 100, but I don't think I can increase that amount via the config file like I can with the rest.

**Comment by QualityRobD** [comment]
Everything looks good. great job @Jimk72, ty again.
![image](https://github.com/user-attachments/assets/623132bc-aa76-4e02-bc35-64b6a2d0e584)
