### ISSUE TITLE
Windmill Generator takes weather effects

### ISSUE THREAD

**Issue by BeardMagics** [Jimk72/Icarus_Mods#38]
Wasn't sure where to post this as I tried to enter into a modding discord to send a message versus a post.

With the windmill generators, they are taking weather damage currently since the newest update.

I verified in the mod source that EffectedByWeather is set to false; and confirmed the mod is compiled correctly and working. The only items I have changed inside it to suit my play is the leather was set to Copper Nail at a value of 20. Noticed the issue right away, removed the mod and downloaded again via IMM 2.2.3 and only changed the value from 5000 to 8000 for the energy generation. Same issue persisted.

Removed again, fresh copy, no changes and the issue is still persistent. I believe they may have changed the weather call in the API and as such the windmill generators now take weather damage.

![image](https://github.com/user-attachments/assets/755cb724-0323-46f6-a6aa-da72e2507ebd)

**Comment by Jimk72** [comment]
This is now fixed. Should no longer take damage. Also redid the large wind turbine to remove damage modifiers.
