### ISSUE TITLE
Teleporter - Dedicated Server, drops users

### ISSUE THREAD

**Issue by munsterlander** [Jimk72/Icarus_Mods#39]
We have the pak file on the server, but that didn't seem to show up in the workshop for either of us. We each installed the mod locally and that works, but one user experiences a weird lag every so often with it installed. If they remove the mod, then they do not experience the lag; however, when the other user now teleports, it kicks them from the server. 

Very open to helping to debug and test this.  We are both devs, just new to the realm of mods and their language.

**Comment by Jimk72** [comment]
When using mods in Icarus, the same pak file has to be on the server, and all the clients. If you are not using a server, everyone that connects to the host player including the host has to have the same pak file. If one client does not have the same pak file you will see weird issues with the game and the UI based off what the mod files contain.

**Comment by Jimk72** [comment]
Let me know if this helps fix the issue.

**Comment by munsterlander** [comment]
It has helped a bit.  We made sure that all of us are running the exact same PAK files for all mods - which is just your progression one and the teleporter.  We are not using the IMM to do these just to make sure, but the server and both local machines are the exact same.  After you teleport, there is lag but overall game play has been consistent.  One thing we have noticed - with this weeks update and not certain if its that or the mod - but random things just disappear from the game or don't work.  Like one section of wall in our building that has been there forever, a fabricator, etc.

**Comment by Jimk72** [comment]
That's the game. Always has been an issue. The worst is when a storage cabinet disappears that's full of ore. This week there is also nvidia drivers issues that are causing lag and stutters and sometimes crashes.

**Comment by Bulldogg55** [comment]
we added your mod to the server and now the server will not boot up. is there an issue that we can do that or is there a way just to add the mods we want to add? but first the mod and not able to boot up the server, not sure what we did wrong, we run off a server no a host player

**Comment by Jimk72** [comment]
You created the pak file using the mod manager and then added that pak file to your server and all clients correct?

**Comment by Bulldogg55** [comment]
From my server manager:

doesnt work that way on survival servers, you have to manually put them where they go

Wes
________________________________

**Comment by munsterlander** [comment]
You have to create the path.  We use Windows Game Server on our own dedicated machine, but that path was something like windowsgsm/servers/1/Icarus/content/paks/mod or what not. Sorry I don't have the exact path as I'm on mobile, but basically set it up like you would on local. 

It works for us other than some random things, but it's saved us a ton of time in the null sector shuttling materials.

**Comment by munsterlander** [comment]
Closing because it did work for us with @Jimk72's advice.

**Comment by Bulldogg55** [comment]
Thank you for your time and if you get a chance when you get home could you send me the instructions for adding the mod and the manager and a how to install.

thanks
 much appreciated

Wes
________________________________
