### ISSUE TITLE
Leveling Mod not Enough Talent Points

### ISSUE THREAD

**Issue by stephbackv2** [Jimk72/Icarus_Mods#42]
Hey,
I'm using the mod manager with great pleasure, but i have a little problem with you leveling mod. So I'm above level 200 and do not get any talent points anymore, but there are still some talents open that i don't have on the character. Is there some way to fix this/ get them anyway?

**Comment by Jimk72** [comment]
How many more points are needed.

**Comment by stephbackv2** [comment]
I'm missing 11 Talent Points to complete the tech tree

**Comment by Jimk72** [comment]
Adjusted to 550 in version 3.3 which is now uploaded.

**Comment by stephbackv2** [comment]
works like a charm, thank you!
