### ISSUE TITLE
Not an issue, but a question

### ISSUE THREAD

**Issue by Cached42** [Jimk72/Icarus_Mods#5]
Hi Jim :) Thanks for posting your work on this for us! I'm writing about the LevelingMod-tempfix. I had hoped to edit that exmod and plug in the values I wanted to use. Basically to keep the vanilla leveling but increase the three different points per level attributes. Simple enough, but I don't see these changes on a new test character.

I'm using your mod manager 

Could you please offer any guidance?

**Comment by Jimk72** [comment]
That mod relies on the uasset files so you would need to use the program called uassetGUI. It’s a curve type so you specify the amount at each level and the game fills in the gaps. Sent from my iPhoneOn Jan 2, 2023, at 10:42 AM, Cached42 ***@***.***> wrote:﻿
Hi Jim :) Thanks for posting your work on this for us! I'm writing about the LevelingMod-tempfix. I had hoped to edit that exmod and plug in the values I wanted to use. Basically to keep the vanilla leveling but increase the three different pints per level attributes. Simple enough, but I don't see these changes on a new test character.
I'm using your mod manager
Could you please offer any guidance?
