### ISSUE TITLE
More_Daylight

### ISSUE THREAD

**Issue by Haalk2715** [Jimk72/Icarus_Mods#6]
Hi Jim,

Again thank you for all your great work (mods)
Any chance we can edit or manage day and night for my Open World Dedicated Server?
Its pretty impossible to get 6 to 8 players it seems to all use bedrolls at same time to force 7:00 am for daylight
Can we edit the cycle?  Like 6:00 am to 10:00 pm and have it just cycle these time and not do full dark nights?

Thx
Haalk

**Comment by Jimk72** [comment]
If you use my mod manager you can right click the mod in the left column and select edit. This will pop up an editor. Just click the items on left and the lists will populate. Try changing and then click save and close it and then add to game and see if it helps. Sent from my iPhoneOn Jan 3, 2023, at 5:24 AM, Haalk2715 ***@***.***> wrote:﻿
Hi Jim,
Again thank you for all your great work (mods)
Any chance we can edit or manage day and night?
Its pretty impossible to get 6 to 8 players it seems to all use bedrolls at same time to force 7:00 am for daylight
Can we edit the cycle?  Like 6:00 am to 10:00 pm and have it just cycle these time and not do full dark nights?
Thx
Haalk

**Comment by Haalk2715** [comment]
Ok thank you, will try that out!
